---
- name: Get Kubernetes inventory
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_remote_tmp: "/tmp/ansible-$USER"
  tasks:
    - name: Fetch existing pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default
      register: pod_info

    - name: Add running pods to fact
      ansible.builtin.set_fact:
        pods: "{{ pod_info.resources }}"
