---
- name: Get Kubernetes inventory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Fetch existing deployments
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: default
      register: deployment_info

    - name: Add running deployments to fact
      ansible.builtin.set_fact:
        deployments: "{{ deployment_info.resources }}"
