---
- name: Get Kubernetes inventory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Fetch existing pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default
      register: pod_info

    - name: Add running pods to inventory
      ansible.builtin.add_host:
        name: "pod-{{ item.metadata.name }}"
        groups: minikube_pods
        ansible_connection: kubernetes.core.kubectl
        ansible_kubectl_pod: "{{ item.metadata.name }}"
      loop: "{{ pod_info.resources }}"
      when: item.status.phase == "Running"

- name: My first play
  hosts: minikube_pods
  gather_facts: false
  tasks:
    - name: Verify pod access
      ansible.builtin.raw:
        echo "Successful connection to {{ ansible_kubectl_pod }}"
      register: connection_test
      changed_when: false

    - name: Show connection proof
      ansible.builtin.debug:
        msg: "{{ connection_test.stdout }}"
