---
- name: Get Kubernetes inventory
  ansible.builtin.import_playbook: get_inventory.yml

- name: Check kube version
  hosts: localhost
  connection: local
  tasks:
    - name: Check kubectl version
      ansible.builtin.raw:
        kubectl version
      changed_when: false
    - name: Check kubernetes package version
      ansible.builtin.raw:
        pip show kubernetes
      changed_when: false


- name: My first play
  hosts: minikube_pods
  connection: kubernetes.core.kubectl
  gather_facts: false
  vars:
    ansible_remote_tmp: "/tmp/ansible-$USER"
    ansible_kubectl_extra_args: --insecure-skip-tls-verify=False
  tasks:
    - name: Verify pod access
      ansible.builtin.raw:
        echo "Successful connection to {{ ansible_kubectl_pod }}"
      register: connection_test
      changed_when: false

    - name: Show connection proof
      ansible.builtin.debug:
        msg: "{{ connection_test.stdout }}"
