---
- name: Get Kubernetes inventory
  ansible.builtin.import_playbook: get_inventory.yml

- name: My first play
  hosts: minikube_pods
  connection: kubernetes.core.kubectl
  gather_facts: false
  vars:
    ansible_kubectl_extra_args: |
      --server={{ lookup('env', 'K8S_AUTH_HOST') }}
      --token={{ lookup('env', 'K8S_AUTH_API_KEY') }}
      --insecure-skip-tls-verify
    ansible_kubectl_namespace: "{{ lookup('env', 'K8S_AUTH_NAMESPACE') | default('default', true) }}"
  tasks:
    - name: Verify pod access
      ansible.builtin.raw:
        echo "Successful connection to {{ ansible_kubectl_pod }}"
      register: connection_test
      changed_when: false

    - name: Show connection proof
      ansible.builtin.debug:
        msg: "{{ connection_test.stdout }}"
