---
- name: Get Kubernetes inventory
  ansible.builtin.import_playbook: get_inventory.yml

- name: Manage pods
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_remote_tmp: "/tmp/ansible-$USER"
  tasks:
    - name: Collect running pods to inventory
      ansible.builtin.add_host:
        name: "{{ item.metadata.name }}"
        ansible_connection: local
        ansible_kubectl_pod: "{{ item.metadata.name }}"
      changed_when: false
      when: item.status.phase == "Running"
      loop: "{{ pods }}"

- name: Serve with nginx
  hosts: localhost
  connection: local
  vars:
    ansible_remote_tmp: "/tmp/ansible-$USER"
  gather_facts: false
  tasks:
    - name: Get nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      delegate_to: "{{ item.metadata.name }}"
      loop: "{{ pods }}"

    - name: Copy index.html
      ansible.builtin.copy:
        src: /home/turosigor/practices/ansible-practice/k8s/index.html
        dest: /usr/share/nginx/index.html
        mode: '0644'
        remote_src: false
      delegate_to: "{{ item.metadata.name }}"
      loop: "{{ pods }}"

    - name: Attach nginx.conf ConfigMap
      kubernetes.core.k8s:
        state: patched
        kind: Pod
        name: "{{ item.metadata.name }}"
        definition:
          spec:
            containers:
              volumeMounts:
                - name: nginx.conf
                  mountPath: /etc/nginx/nginx.conf
            volumes:
              - name: nginx.conf
                configMap:
                  name: nginx
      loop: "{{ pods }}"

    - name: Create exposing service
      kubernetes.core.k8s:
        state: present
        definition:
          api_version: v1
          kind: Service
          metadata:
            name: webhost-http
            namespace: default
          spec:
            type: NodePort
            selector:
              app: webhost
            ports:
              - protocol: TCP
                targetPort: 80
                port: 80

    - name: Start nginx
      ansible.builtin.command: nginx -g daemon off;
      changed_when: true
      loop: "{{ pods }}"
