---
- name: Get Kubernetes inventory
  ansible.builtin.import_playbook: get_inventory.yml

- name: Scale deployments
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Scale up to 5 replicas
      kubernetes.core.k8s_scale:
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.metadata.name }}"
        namespace: default
        replicas: 5
      loop: "{{ deployments }}"

    - name: Get pods of deployments
      kubernetes.core.k8s_info:
        kind: Pod
        wait: true
        wait_sleep: 30
        wait_timeout: 300
        namespace: default
        label_selectors:
          - "app = {{ item.metadata.name }}"
      with_items: "{{ deployments }}"
      register: pods

    - name: Show pod count
      ansible.builtin.debug:
        msg: "Number of replicas in deployment {{ item.item.metadata.name }}: {{ item.resources[0] | length }}"
      loop: "{{ pods.results }}"

    - name: Scale down to 3 replicas
      kubernetes.core.k8s_scale:
        api_version: v1
        kind: Deployment
        namespace: default
        name: "{{ item.metadata.name }}"
        replicas: 3
      loop: "{{ deployments }}"
