---
- name: Provision inventory
  ansible.builtin.import_playbook: get_inventory.yml

- name: My first play
  hosts: minikube_pods
  connection: kubernetes.core.kubectl
  become: true
  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        msg: "Hello from {{ ansible_host }}"
