---
- name: Get Kubernetes inventory
  ansible.builtin.import_playbook: get_inventory.yml

- name: Manage pods
  hosts: localhost
  connection: kubectl
  become: true
  gather_facts: false
  tasks:
    - name: Verify pod access
      kubernetes.core.k8s_exec:
        namespace: default
        pod: "{{ item.metadata.name }}"
        command: echo "Successful connection to {{ item.metadata.name }}"
      changed_when: false
      when: item.status.phase == "Running"
      loop: "{{ pods }}"
      register: connection_test

    - name: Show connection proof
      ansible.builtin.debug:
        msg: "{{ item.stdout }}"
      loop: "{{ connection_test.results }}"
