---
- name: Verify cluster health
  hosts: localhost
  connection: local
  tasks:
    - name: Verify pod existence
      ansible.builtin.include_role:
        name: verify-pods
      vars:
        pod_name: loki
        pod_namespace: loki

    - name: Verify service health
      ansible.builtin.include_role:
        name: verify-in-cluster-service
      vars:
        service_name: kubernetes
        service_namespace: default
        protocol: https
        path: 'readyz'
        validate_certs: false

    - name: Verify external domain
      ansible.builtin.include_role:
        name: verify-external-domain
      vars:
        route_name: taboo
        service_namespace: taboo
        protocol: http
        validate_certs: false
