---
- name: Verify cluster health
  hosts: localhost
  connection: local
  tasks:
    - name: Verify Node presence
      ansible.builtin.include_role:
        name: verify-nodes

    - name: Verify pod existence
      ansible.builtin.include_role:
        name: verify-pods
      vars:
        pod_name: awx-web
        pod_namespace: awx
