---
- name: Verify cluster health
  hosts: localhost
  connection: local
  tasks:
    - name: Verify pod existence
      ansible.builtin.include_role:
        name: verify-pods
      vars:
        pod_name: grafana
        pod_namespace: grafana

    - name: Verify service health
      ansible.builtin.include_role:
        name: verify-in-cluster-service
      vars:
        service_name: kube-prometheus-stack-operator
        service_namespace: prometheus
        protocol: http
        path: ''
