---
- name: Ensure component exists
  kubernetes.core.k8s_info:
    kind: "{{ component_kind }}"
    name: "{{ item }}"
  register: k8s_component_results
  loop: "{{ components }}"

- name: Store component by type
  ansible.builtin.set_fact:
    "{{ component_kind | lower }}s": "{{ item.resources }}"
  loop: "{{ k8s_component_results.results }}"
  failed_when: item.resources | length == 0
  when: item.resources is defined
