apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webhost
  template:
    metadata:
      labels:
        app: webhost
    spec:
      containers:
      - name: webhost
        image: ubuntu_ssh:1.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 22
