---
- name: Get all cluster nodes
  kubernetes.core.k8s_info:
    kind: Node
  register: nodes

- name: Check node readiness
  ansible.builtin.fail:
    msg: "{{ item.metadata.name }} NOT ready (status: {{ item.status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | first }})"
  loop: "{{ nodes.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"
  when: >
    item.status.conditions | selectattr('type','equalto','Ready') | map(attribute='status') | first != 'True'
